package com.saq.emproaster;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DayOffRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.saq.emproaster.Employee employee;
	private int weight;

	public DayOffRequest() {
	}

	public com.saq.emproaster.Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(com.saq.emproaster.Employee employee) {
		this.employee = employee;
	}

	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	public DayOffRequest(com.saq.emproaster.Employee employee, int weight) {
		this.employee = employee;
		this.weight = weight;
	}

}