package com.saq.emproaster;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShiftDate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int dayIndex;
	private java.lang.String dateString;

	private com.saq.emproaster.DayOfWeek dayOfWeek;

	private java.util.List<com.saq.emproaster.Shift> shiftList;

	public ShiftDate() {
	}

	public int getDayIndex() {
		return this.dayIndex;
	}

	public void setDayIndex(int dayIndex) {
		this.dayIndex = dayIndex;
	}

	public java.lang.String getDateString() {
		return this.dateString;
	}

	public void setDateString(java.lang.String dateString) {
		this.dateString = dateString;
	}

	public com.saq.emproaster.DayOfWeek getDayOfWeek() {
		return this.dayOfWeek;
	}

	public void setDayOfWeek(com.saq.emproaster.DayOfWeek dayOfWeek) {
		this.dayOfWeek = dayOfWeek;
	}

	public java.util.List<com.saq.emproaster.Shift> getShiftList() {
		return this.shiftList;
	}

	public void setShiftList(java.util.List<com.saq.emproaster.Shift> shiftList) {
		this.shiftList = shiftList;
	}

    public int getWeekendSundayIndex() {
        switch (dayOfWeek) {
            case MONDAY:
                return dayIndex - 1;
            case TUESDAY:
                return dayIndex - 2;
            case WEDNESDAY:
                return dayIndex - 3;
            case THURSDAY:
                return dayIndex + 3;
            case FRIDAY:
                return dayIndex + 2;
            case SATURDAY:
                return dayIndex + 1;
            case SUNDAY:
                return dayIndex;
            default:
                throw new IllegalArgumentException("The dayOfWeek (" + dayOfWeek + ") is not valid.");
        }
    }
	public ShiftDate(int dayIndex, java.lang.String dateString,
			com.saq.emproaster.DayOfWeek dayOfWeek,
			java.util.List<com.saq.emproaster.Shift> shiftList) {
		this.dayIndex = dayIndex;
		this.dateString = dateString;
		this.dayOfWeek = dayOfWeek;
		this.shiftList = shiftList;
	}

}