package com.saq.emproaster;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShiftOnRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ShiftOnRequest() {
    }




}