package com.saq.emproaster;
import java.util.Set;
import java.util.TreeSet;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShiftType implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String code;
	private int index;
	private java.lang.String startTimeString;
	private java.lang.String endTimeString;
	private boolean night;
	private java.lang.String description;
	private Set<Skill> skills = new TreeSet<>();

	public ShiftType() {
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public int getIndex() {
		return this.index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public java.lang.String getStartTimeString() {
		return this.startTimeString;
	}

	public void setStartTimeString(java.lang.String startTimeString) {
		this.startTimeString = startTimeString;
	}

	public java.lang.String getEndTimeString() {
		return this.endTimeString;
	}

	public void setEndTimeString(java.lang.String endTimeString) {
		this.endTimeString = endTimeString;
	}

	public boolean isNight() {
		return this.night;
	}

	public void setNight(boolean night) {
		this.night = night;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}
    public Set<Skill> getSkills() {
        return skills;
    }
    public void setSkills(Set<Skill> skills) {
        this.skills = skills;
    }

    public ShiftType addSkill(Skill skill) {
        getSkills().add(skill);
        return this;
    }

   
    public ShiftType removeSkill(Skill skill) {
        getSkills().remove(skill);
        return this;
    }
	public ShiftType(java.lang.String code, int index,
			java.lang.String startTimeString, java.lang.String endTimeString,
			boolean night, java.lang.String description) {
		this.code = code;
		this.index = index;
		this.startTimeString = startTimeString;
		this.endTimeString = endTimeString;
		this.night = night;
		this.description = description;
	}

}