package com.saq.emproaster;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Shift implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Shift() {
    }




}