package com.saq.emproaster;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Skill implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String code;

	public Skill() {
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public Skill(java.lang.String code) {
		this.code = code;
	}

}